package com.olive.rest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.olive.model.User;
import com.olive.user.request.UserRequest;
import com.olive.user.response.UserResponse;
import com.olive.user.service.IUserService;
import com.olive.utils.JwtUtils;

@RestController
@RequestMapping("/user")
public class UserController {
	@Autowired
	private AuthenticationManager auth;

	@Autowired
	private IUserService service;

	@Autowired
	private JwtUtils jwt;

	@PostMapping("/save")
	public ResponseEntity<String> saveUser(@RequestBody User user){
		Integer id = service.saveUser(user);
		return new ResponseEntity<String>("User save with "+id+"id", HttpStatus.OK);
	}

	@PostMapping("/login")
	public ResponseEntity<UserResponse> login(@RequestBody UserRequest req){
		auth.authenticate(new UsernamePasswordAuthenticationToken(
				req.getUsername(),
				req.getPassword()));
		          
		String token = jwt.generateToken(req.getUsername());
		
		return new ResponseEntity<UserResponse>(new UserResponse(token,"Generated BY Mr. Ravi")
				, HttpStatus.OK);
	}
	
	@PostMapping("/home")
	public ResponseEntity<String> secure(){
		
		return  ResponseEntity.ok("Welcome Page After Login Success ......");
	}

	
}
